//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace NtAbcExam.Domain.Models
{
    /// <summary>
    /// 实体类cadre_info。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("cadre_info")]
    [Serializable]
    public partial class cadre_info : Entity
    {
        #region Model
        private int _Id;
        private string _UserID;
        private string _UserName;
        private string _Pwd;
        private int _DeptId;
        private string _Office;
        private string _Duties;
        private string _Rank;
        private string _Post;
        private string _Spower;

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserID")]
        public string UserID
        {
            get { return _UserID; }
            set
            {
                this.OnPropertyValueChange("UserID");
                this._UserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserName")]
        public string UserName
        {
            get { return _UserName; }
            set
            {
                this.OnPropertyValueChange("UserName");
                this._UserName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Pwd")]
        public string Pwd
        {
            get { return _Pwd; }
            set
            {
                this.OnPropertyValueChange("Pwd");
                this._Pwd = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeptId")]
        public int DeptId
        {
            get { return _DeptId; }
            set
            {
                this.OnPropertyValueChange("DeptId");
                this._DeptId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Office")]
        public string Office
        {
            get { return _Office; }
            set
            {
                this.OnPropertyValueChange("Office");
                this._Office = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Duties")]
        public string Duties
        {
            get { return _Duties; }
            set
            {
                this.OnPropertyValueChange("Duties");
                this._Duties = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Rank")]
        public string Rank
        {
            get { return _Rank; }
            set
            {
                this.OnPropertyValueChange("Rank");
                this._Rank = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Post")]
        public string Post
        {
            get { return _Post; }
            set
            {
                this.OnPropertyValueChange("Post");
                this._Post = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Spower")]
        public string Spower
        {
            get { return _Spower; }
            set
            {
                this.OnPropertyValueChange("Spower");
                this._Spower = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.UserID,
                _.UserName,
                _.Pwd,
                _.DeptId,
                _.Office,
                _.Duties,
                _.Rank,
                _.Post,
                _.Spower,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._UserID,
                this._UserName,
                this._Pwd,
                this._DeptId,
                this._Office,
                this._Duties,
                this._Rank,
                this._Post,
                this._Spower,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "cadre_info");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserID = new Field("UserID", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserName = new Field("UserName", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Pwd = new Field("Pwd", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Office = new Field("Office", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Duties = new Field("Duties", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Rank = new Field("Rank", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Post = new Field("Post", "cadre_info", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Spower = new Field("Spower", "cadre_info", "");
        }
        #endregion
    }
}

