//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NtAbcExam.Domain.Models
{

    /// <summary>
    /// 实体类exam_database。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("exam_database")]
    [Serializable]
    public partial class exam_database : Entity
    {
        #region Model
        private int _Id;
        private int _DeptId;
        private int _SubjectId;
        private string _Question;
        private string _Type;
        private string _Text1;
        private string _Text2;
        private string _Text3;
        private string _Text4;
        private string _Text5;
        private string _Text6;
        private string _Answer;
        private float? _Mark;

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeptId")]
        public int DeptId
        {
            get { return _DeptId; }
            set
            {
                this.OnPropertyValueChange("DeptId");
                this._DeptId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SubjectId")]
        public int SubjectId
        {
            get { return _SubjectId; }
            set
            {
                this.OnPropertyValueChange("SubjectId");
                this._SubjectId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Question")]
        public string Question
        {
            get { return _Question; }
            set
            {
                this.OnPropertyValueChange("Question");
                this._Question = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Type")]
        public string Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Text1")]
        public string Text1
        {
            get { return _Text1; }
            set
            {
                this.OnPropertyValueChange("Text1");
                this._Text1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Text2")]
        public string Text2
        {
            get { return _Text2; }
            set
            {
                this.OnPropertyValueChange("Text2");
                this._Text2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Text3")]
        public string Text3
        {
            get { return _Text3; }
            set
            {
                this.OnPropertyValueChange("Text3");
                this._Text3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Text4")]
        public string Text4
        {
            get { return _Text4; }
            set
            {
                this.OnPropertyValueChange("Text4");
                this._Text4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Text5")]
        public string Text5
        {
            get { return _Text5; }
            set
            {
                this.OnPropertyValueChange("Text5");
                this._Text5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Text6")]
        public string Text6
        {
            get { return _Text6; }
            set
            {
                this.OnPropertyValueChange("Text6");
                this._Text6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Answer")]
        public string Answer
        {
            get { return _Answer; }
            set
            {
                this.OnPropertyValueChange("Answer");
                this._Answer = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Mark")]
        public float? Mark
        {
            get { return _Mark; }
            set
            {
                this.OnPropertyValueChange("Mark");
                this._Mark = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.DeptId,
                _.SubjectId,
                _.Question,
                _.Type,
                _.Text1,
                _.Text2,
                _.Text3,
                _.Text4,
                _.Text5,
                _.Text6,
                _.Answer,
                _.Mark,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._DeptId,
                this._SubjectId,
                this._Question,
                this._Type,
                this._Text1,
                this._Text2,
                this._Text3,
                this._Text4,
                this._Text5,
                this._Text6,
                this._Answer,
                this._Mark,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "exam_database");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SubjectId = new Field("SubjectId", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Question = new Field("Question", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Text1 = new Field("Text1", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Text2 = new Field("Text2", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Text3 = new Field("Text3", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Text4 = new Field("Text4", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Text5 = new Field("Text5", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Text6 = new Field("Text6", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Answer = new Field("Answer", "exam_database", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Mark = new Field("Mark", "exam_database", "");
        }
        #endregion
    }

}

