//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace NtAbcExam.Domain.Models
{

    /// <summary>
    /// 实体类exam_testuser。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("exam_testuser")]
    [Serializable]
    public partial class exam_testuser : Entity
    {
        #region Model
        private int _Id;
        private int _TestId;
        private string _UserId;
        private int _HaveTest;

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TestId")]
        public int TestId
        {
            get { return _TestId; }
            set
            {
                this.OnPropertyValueChange("TestId");
                this._TestId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserId")]
        public string UserId
        {
            get { return _UserId; }
            set
            {
                this.OnPropertyValueChange("UserId");
                this._UserId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("HaveTest")]
        public int HaveTest
        {
            get { return _HaveTest; }
            set
            {
                this.OnPropertyValueChange("HaveTest");
                this._HaveTest = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.TestId,
                _.UserId,
                _.HaveTest,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._TestId,
                this._UserId,
                this._HaveTest,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "exam_testuser");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "exam_testuser", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TestId = new Field("TestId", "exam_testuser", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserId = new Field("UserId", "exam_testuser", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HaveTest = new Field("HaveTest", "exam_testuser", "");
        }
        #endregion
    }

}

