//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace NtAbcExam.Domain.Models
{
    /// <summary>
    /// 实体类exam_score。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("exam_score")]
    [Serializable]
    public partial class exam_score : Entity
    {
        #region Model
        private int _Id;
        private string _UserId;
        private string _UserName;
        private int _DeptId;
        private string _Office;
        private string _Duties;
        private int _SubjectId;
        private int _TestId;
        private DateTime? _StartTime;
        private DateTime? _EndTime;
        private decimal _Score;
        private string _Wrong_Dan;
        private string _Wrong_Duo;
        private string _Wrong_Pd;

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserId")]
        public string UserId
        {
            get { return _UserId; }
            set
            {
                this.OnPropertyValueChange("UserId");
                this._UserId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserName")]
        public string UserName
        {
            get { return _UserName; }
            set
            {
                this.OnPropertyValueChange("UserName");
                this._UserName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeptId")]
        public int DeptId
        {
            get { return _DeptId; }
            set
            {
                this.OnPropertyValueChange("DeptId");
                this._DeptId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Office")]
        public string Office
        {
            get { return _Office; }
            set
            {
                this.OnPropertyValueChange("Office");
                this._Office = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Duties")]
        public string Duties
        {
            get { return _Duties; }
            set
            {
                this.OnPropertyValueChange("Duties");
                this._Duties = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SubjectId")]
        public int SubjectId
        {
            get { return _SubjectId; }
            set
            {
                this.OnPropertyValueChange("SubjectId");
                this._SubjectId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TestId")]
        public int TestId
        {
            get { return _TestId; }
            set
            {
                this.OnPropertyValueChange("TestId");
                this._TestId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("StartTime")]
        public DateTime? StartTime
        {
            get { return _StartTime; }
            set
            {
                this.OnPropertyValueChange("StartTime");
                this._StartTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("EndTime")]
        public DateTime? EndTime
        {
            get { return _EndTime; }
            set
            {
                this.OnPropertyValueChange("EndTime");
                this._EndTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Score")]
        public decimal Score
        {
            get { return _Score; }
            set
            {
                this.OnPropertyValueChange("Score");
                this._Score = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Wrong_Dan")]
        public string Wrong_Dan
        {
            get { return _Wrong_Dan; }
            set
            {
                this.OnPropertyValueChange("Wrong_Dan");
                this._Wrong_Dan = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Wrong_Duo")]
        public string Wrong_Duo
        {
            get { return _Wrong_Duo; }
            set
            {
                this.OnPropertyValueChange("Wrong_Duo");
                this._Wrong_Duo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Wrong_Pd")]
        public string Wrong_Pd
        {
            get { return _Wrong_Pd; }
            set
            {
                this.OnPropertyValueChange("Wrong_Pd");
                this._Wrong_Pd = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.UserId,
                _.UserName,
                _.DeptId,
                _.Office,
                _.Duties,
                _.SubjectId,
                _.TestId,
                _.StartTime,
                _.EndTime,
                _.Score,
                _.Wrong_Dan,
                _.Wrong_Duo,
                _.Wrong_Pd,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._UserId,
                this._UserName,
                this._DeptId,
                this._Office,
                this._Duties,
                this._SubjectId,
                this._TestId,
                this._StartTime,
                this._EndTime,
                this._Score,
                this._Wrong_Dan,
                this._Wrong_Duo,
                this._Wrong_Pd,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "exam_score");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserId = new Field("UserId", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserName = new Field("UserName", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Office = new Field("Office", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Duties = new Field("Duties", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SubjectId = new Field("SubjectId", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TestId = new Field("TestId", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StartTime = new Field("StartTime", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field EndTime = new Field("EndTime", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Wrong_Dan = new Field("Wrong_Dan", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Wrong_Duo = new Field("Wrong_Duo", "exam_score", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Wrong_Pd = new Field("Wrong_Pd", "exam_score", "");
        }
        #endregion
    }

}

