//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NtAbcExam.Domain.Models
{

	/// <summary>
	/// 实体类exam_news 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("exam_news")]
	[Serializable]
	public partial class exam_news : Entity 
	{
		#region Model
		private int _Id;
		private int? _NewsId;
		private string _Title;
		private string _Text;
		private int? _Youxq;
		private DateTime? _Fabsj;
		private string _Fabr;
		private int? _PassUserId;
		private string _PassTime;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? NewsId
		{
			get{ return _NewsId; }
			set
			{
				this.OnPropertyValueChange(_.NewsId,_NewsId,value);
				this._NewsId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Text
		{
			get{ return _Text; }
			set
			{
				this.OnPropertyValueChange(_.Text,_Text,value);
				this._Text=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Youxq
		{
			get{ return _Youxq; }
			set
			{
				this.OnPropertyValueChange(_.Youxq,_Youxq,value);
				this._Youxq=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Fabsj
		{
			get{ return _Fabsj; }
			set
			{
				this.OnPropertyValueChange(_.Fabsj,_Fabsj,value);
				this._Fabsj=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Fabr
		{
			get{ return _Fabr; }
			set
			{
				this.OnPropertyValueChange(_.Fabr,_Fabr,value);
				this._Fabr=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PassUserId
		{
			get{ return _PassUserId; }
			set
			{
				this.OnPropertyValueChange(_.PassUserId,_PassUserId,value);
				this._PassUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PassTime
		{
			get{ return _PassTime; }
			set
			{
				this.OnPropertyValueChange(_.PassTime,_PassTime,value);
				this._PassTime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.NewsId,
				_.Title,
				_.Text,
				_.Youxq,
				_.Fabsj,
				_.Fabr,
				_.PassUserId,
				_.PassTime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._NewsId,
				this._Title,
				this._Text,
				this._Youxq,
				this._Fabsj,
				this._Fabr,
				this._PassUserId,
				this._PassTime};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","exam_news");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","exam_news","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NewsId = new Field("NewsId","exam_news","NewsId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","exam_news","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Text = new Field("Text","exam_news","Text");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Youxq = new Field("Youxq","exam_news","Youxq");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Fabsj = new Field("Fabsj","exam_news","Fabsj");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Fabr = new Field("Fabr","exam_news","Fabr");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PassUserId = new Field("PassUserId","exam_news","PassUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PassTime = new Field("PassTime","exam_news","PassTime");
		}
		#endregion


	}
}

