//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NtAbcExam.Domain.Models
{

	/// <summary>
	/// 实体类waitforpass 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("waitforpass")]
	[Serializable]
	public partial class waitforpass : Entity 
	{
		#region Model
		private int _Id;
		private string _ObjName;
		private int? _ObjId;
		private int? _PassUserId;
		private string _PassAdvice;
		private DateTime? _PassTime;
		private int? _HavePass;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ObjName
		{
			get{ return _ObjName; }
			set
			{
				this.OnPropertyValueChange(_.ObjName,_ObjName,value);
				this._ObjName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ObjId
		{
			get{ return _ObjId; }
			set
			{
				this.OnPropertyValueChange(_.ObjId,_ObjId,value);
				this._ObjId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PassUserId
		{
			get{ return _PassUserId; }
			set
			{
				this.OnPropertyValueChange(_.PassUserId,_PassUserId,value);
				this._PassUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PassAdvice
		{
			get{ return _PassAdvice; }
			set
			{
				this.OnPropertyValueChange(_.PassAdvice,_PassAdvice,value);
				this._PassAdvice=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? PassTime
		{
			get{ return _PassTime; }
			set
			{
				this.OnPropertyValueChange(_.PassTime,_PassTime,value);
				this._PassTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? HavePass
		{
			get{ return _HavePass; }
			set
			{
				this.OnPropertyValueChange(_.HavePass,_HavePass,value);
				this._HavePass=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ObjName,
				_.ObjId,
				_.PassUserId,
				_.PassAdvice,
				_.PassTime,
				_.HavePass};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ObjName,
				this._ObjId,
				this._PassUserId,
				this._PassAdvice,
				this._PassTime,
				this._HavePass};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","waitforpass");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","waitforpass","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ObjName = new Field("ObjName","waitforpass","ObjName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ObjId = new Field("ObjId","waitforpass","ObjId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PassUserId = new Field("PassUserId","waitforpass","PassUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PassAdvice = new Field("PassAdvice","waitforpass","PassAdvice");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PassTime = new Field("PassTime","waitforpass","PassTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HavePass = new Field("HavePass","waitforpass","HavePass");
		}
		#endregion


	}
}

